import { useEffect, useState } from 'react';

const tasks:[string,number,string][]=[
['2³ + 3² = ?',17,'СТЕПЕНИ'],['5² − 3² = ?',16,'СТЕПЕНИ'],['10² ÷ 10 = ?',10,'СТЕПЕНИ'],['3 · 2⁴ = ?',48,'СТЕПЕНИ'],
['4x + 7 = 19. x = ?',3,'УРАВНЕНИЯ'],['5x − 10 = 20. x = ?',6,'УРАВНЕНИЯ'],['2x + 4 = 18. x = ?',7,'УРАВНЕНИЯ'],['7x = 49. x = ?',7,'УРАВНЕНИЯ'],
['Квадрат со стороной 6. Периметр?',24,'ГЕОМЕТРИЯ'],['Квадрат со стороной 7. Площадь?',49,'ГЕОМЕТРИЯ'],['Прямоугольник 5×8. Площадь?',40,'ГЕОМЕТРИЯ'],['Прямоугольник 4×9. Периметр?',26,'ГЕОМЕТРИЯ'],
['2⁵ − 2³ = ?',24,'СТЕПЕНИ'],['3³ + 2² = ?',31,'СТЕПЕНИ'],['3x + 2 = 17. x = ?',5,'УРАВНЕНИЯ'],['9x − 9 = 36. x = ?',5,'УРАВНЕНИЯ'],
['Треугольник 5, 6, 7. Периметр?',18,'ГЕОМЕТРИЯ'],['Периметр прямоугольника 30, сторона 5. Вторая?',10,'ГЕОМЕТРИЯ'],['6² + 8² = ?',100,'СЧЁТ'],['10³ ÷ 10² = ?',10,'СТЕПЕНИ'],
['4x − 8 = 24. x = ?',8,'УРАВНЕНИЯ'],['6x + 6 = 42. x = ?',6,'УРАВНЕНИЯ'],['90° — прямой угол. Введите 1.',1,'ГЕОМЕТРИЯ'],['Квадрат со стороной 9. Периметр?',36,'ГЕОМЕТРИЯ'],
['7² − 5² = ?',24,'СТЕПЕНИ'],['2⁶ = ?',64,'СТЕПЕНИ'],['8x = 72. x = ?',9,'УРАВНЕНИЯ'],['2x + 8 = 30. x = ?',11,'УРАВНЕНИЯ'],
['Площадь квадрата 64. Сторона?',8,'ГЕОМЕТРИЯ'],['5³ = ?',125,'СТЕПЕНИ']
];

export default function MathBreak(){
 const [i,setI]=useState(0),[xp,setXp]=useState(0),[streak,setStreak]=useState(0),[best,setBest]=useState(0),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(''),[running,setRunning]=useState(false),[left,setLeft]=useState(1800),[rest,setRest]=useState(0);
 const [finished,setFinished]=useState(false);
 useEffect(()=>{if(!running)return;const t=setInterval(()=>setLeft(v=>Math.max(0,v-1)),1000);return()=>clearInterval(t)},[running]);
 useEffect(()=>{if(running&&left===0)setRunning(false)},[left,running]);
 useEffect(()=>{if(rest<=0)return;const t=setInterval(()=>setRest(v=>Math.max(0,v-1)),1000);return()=>clearInterval(t)},[rest]);
 useEffect(()=>{if(rest===0&&i>0)document.getElementById('mb-answer')?.focus()},[rest,i]);
 const start=()=>{setI(0);setXp(0);setStreak(0);setBest(0);setLeft(1800);setRest(0);setFinished(false);setRunning(true);setAnswer('');setFeedback('')};
 const submit=()=>{if(!running||rest||!answer.trim())return;const ok=Number(answer)===tasks[i][1];const ns=ok?streak+1:0;setStreak(ns);setBest(Math.max(best,ns));setXp(v=>v+(ok?10+Math.min(streak,10)*2:0));setFeedback(ok?'✓ Отлично!':'Не страшно — правильный ответ: '+tasks[i][1]);setAnswer('');setTimeout(()=>{const next=i+1;if(next>=30){setFinished(true);setRunning(false);return}setI(next);setFeedback('');if(next%5===0)setRest(30)},450)};
 const mm=Math.floor(left/60),ss=String(left%60).padStart(2,'0');
 return <div className="math-break">
 <style>{`
 .math-break{min-height:100vh;background:radial-gradient(circle at 15% 10%,#29204d 0,#10131d 38%),#10131d;color:#f7f8fc;padding:22px;font-family:Inter,system-ui,sans-serif}.mb-wrap{max-width:1100px;margin:auto}.mb-top{display:flex;justify-content:space-between;gap:18px;align-items:center;margin-bottom:18px}.mb-brand{font-weight:900;letter-spacing:.12em;font-size:20px}.mb-brand span{color:#22d3ee}.mb-sub{color:#9ca8bd;font-size:12px;margin-top:5px}.mb-hud{display:flex;gap:9px}.mb-pill{background:#171c29dd;border:1px solid #30394f;border-radius:15px;padding:8px 13px}.mb-pill small{display:block;color:#9ca8bd;font-size:9px}.mb-pill b{font-size:19px}.mb-grid{display:grid;grid-template-columns:1fr 285px;gap:16px}.mb-card{background:#171c29ed;border:1px solid #30394f;border-radius:26px;box-shadow:0 20px 60px #0006}.mb-main{padding:30px;min-height:610px;display:flex;flex-direction:column}.mb-tag{color:#22d3ee;font-size:11px;font-weight:900;letter-spacing:.15em}.mb-title{font-size:clamp(30px,5vw,50px);font-weight:900;margin:8px 0}.mb-muted{color:#9ca8bd;line-height:1.5}.mb-progress{height:9px;background:#0d111a;border-radius:99px;overflow:hidden;margin:22px 0}.mb-progress i{display:block;height:100%;background:linear-gradient(90deg,#8b5cf6,#22d3ee);transition:.25s}.mb-q{font-size:clamp(34px,6vw,64px);font-weight:900;text-align:center;padding:35px 5px 24px}.mb-answer{display:flex;gap:10px;max-width:600px;width:100%;margin:auto}.mb-answer input{flex:1;background:#0e121c;color:white;border:2px solid #343e55;border-radius:15px;padding:16px;font-size:23px;text-align:center;outline:0}.mb-answer input:focus{border-color:#22d3ee}.mb-btn{border:0;border-radius:15px;padding:15px 20px;font-weight:900;cursor:pointer}.mb-primary{background:linear-gradient(135deg,#8b5cf6,#6d4df4);color:white}.mb-secondary{background:#293248;color:white}.mb-feedback{text-align:center;min-height:30px;margin:17px;font-weight:900}.mb-side{padding:22px}.mb-stat{padding:14px;border-radius:15px;background:#111622;margin:10px 0}.mb-stat b{font-size:27px}.mb-start{text-align:center;margin-top:auto}.mb-start .mb-btn{font-size:17px;padding:17px 26px}.mb-rest{position:fixed;inset:0;background:#090c13f5;z-index:20;display:flex;align-items:center;justify-content:center;padding:20px}.mb-restbox{max-width:520px;width:100%;text-align:center;padding:40px;border-radius:28px;background:linear-gradient(145deg,#1d2540,#151a29);border:1px solid #3b4763}.mb-restemoji{font-size:64px}.mb-resttime{font-size:58px;font-weight:900;color:#22d3ee}.mb-finish{text-align:center;padding:80px 20px}.mb-back{margin-top:15px}.mb-link{color:#22d3ee;text-decoration:none}@media(max-width:800px){.mb-grid{grid-template-columns:1fr}.mb-side{order:-1}.mb-top{align-items:flex-start;flex-direction:column}.mb-main{padding:22px;min-height:560px}}
 `}</style>
 <div className="mb-wrap">
  <header className="mb-top"><div><div className="mb-brand">MATH<span>//</span>BREAK</div><div className="mb-sub">7 КЛАСС · 30 МИНУТ · МАТЕМАТИЧЕСКАЯ ПЕРЕМЕНА</div></div><div className="mb-hud"><div className="mb-pill"><small>ВРЕМЯ</small><b>{mm}:{ss}</b></div><div className="mb-pill"><small>XP</small><b>{xp}</b></div><div className="mb-pill"><small>СЕРИЯ</small><b>{streak}</b></div></div></header>
  <div className="mb-grid"><section className="mb-card mb-main">{finished?<div className="mb-finish"><div style={{fontSize:70}}>🎉</div><h1>Перемена закончилась!</h1><p className="mb-muted">30 заданий пройдено · {xp} XP · лучшая серия {best}</p><button className="mb-btn mb-primary" onClick={start}>СЫГРАТЬ ЕЩЁ</button></div>:<><div className="mb-tag">{running?tasks[i][2]:'READY'}</div><div className="mb-title">{running?'Раунд '+(Math.floor(i/5)+1):'Переключаем мозг'}</div><div className="mb-muted">{running?'Быстро подумай. Ошибаться можно.':'Короткие задачи, быстрые раунды и мини-паузы. Это не контрольная — это математическая перемена.'}</div><div className="mb-progress"><i style={{width:(i/30*100)+'%'}}/></div>{running?<><div className="mb-q">{tasks[i][0]}</div><div className="mb-answer"><input id="mb-answer" inputMode="numeric" value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} autoFocus/><button className="mb-btn mb-primary" onClick={submit}>ПРОВЕРИТЬ</button></div><div className="mb-feedback">{feedback}</div></>:<div className="mb-start"><button className="mb-btn mb-primary" onClick={start}>НАЧАТЬ ПЕРЕМЕНУ</button></div>}</>}</section>
  <aside className="mb-card mb-side"><h3>🎮 Режим отдыха</h3><p className="mb-muted">5 задач → короткая пауза → следующий раунд. Никакого экзамена.</p><div className="mb-stat">Решено<br/><b>{i}</b> / 30</div><div className="mb-stat">Лучшее комбо<br/><b>{best}</b> 🔥</div><p className="mb-muted">Темы: степени · уравнения · геометрия · устный счёт.</p><a className="mb-link" href="/">← Вернуться в EDU.GAME</a></aside></div>
 </div>
 {rest>0&&<div className="mb-rest"><div className="mb-restbox"><div className="mb-restemoji">🧃</div><h2>Мини-перемена!</h2><p className="mb-muted">30 секунд без задач. Потянись, посмотри вдаль и переключись.</p><div className="mb-resttime">0:{String(rest).padStart(2,'0')}</div></div></div>}
 </div>
}